"""Mathematics Engine for CBC Platform.

Complete, production-grade mathematical foundation:
- Canonical Mathematical AST (ast/)
- Physical Quantities & Dimensional Units (units)
- Deterministic Domain Solvers (solvers/)
- Mathematical Verifier (verifier)
- Standardized Formula Registry (formula_registry)
- Assessment Marking & Rubric Validator (assessment_validator)
- Dynamic Question Generator (question_generator)
- Pedagogical Narration & Audio Simulation (narration_agent, tts_service, simulation_builder)
- Educational Document Schema & Multi-target Renderer (document_schema, document_renderer)
"""
from .assessment_validator import (
    AssessmentAuditReport,
    AssessmentValidator,
    QuestionValidationResult,
    RubricMark,
)
from .ast import (
    Angle,
    BinaryOp,
    Circle,
    Constant,
    CoordinatePlane,
    Dataset,
    DatasetObject,
    Equation,
    Event,
    Expression,
    FractionExpr,
    FrequencyTable,
    GeometryObject,
    Inequality,
    InterestModel,
    Logarithm,
    MathFunction,
    MathObject,
    Money,
    Point,
    Polynomial,
    Power,
    ProbabilityValue,
    Quadrilateral,
    Radical,
    Relation,
    SampleSpace,
    Sector,
    Segment,
    SystemOfEquations,
    TableOfValues,
    Term,
    Triangle,
    Variable,
    Vector,
)
from .context import CurriculumContext, load_context_from_db
from .document_renderer import render_educational_document_html
from .document_schema import DocumentBlock, EducationalDocument
from .formula_registry import (
    FORMULA_REGISTRY,
    MathFormula,
    get_formulas_for_context,
    search_formulas,
)
from .narration_agent import narration_agent
from .objects import (
    MathDataset,
    MathEquation,
    MathExpression,
    MathFraction,
    MathNumber,
    MathPercentage,
    MathPoint,
    MathRatio,
    MathTriangle,
    MathVariable,
    SolutionStep,
    SolutionTrace,
)
from .question_generator import generate_math_question
from .simulation_builder import build_simulation_track
from .simulation_schema import SimulationStep, SimulationTrack
from .solver import (
    prime_factorization,
    solve_circle_properties,
    solve_complementary_probability,
    solve_compound_interest,
    solve_coordinate_distance_midpoint,
    solve_cuboid_volume_and_surface_area,
    solve_cylinder_volume_and_surface_area,
    solve_dataset_summary,
    solve_density_mass_volume,
    solve_elevation_depression,
    solve_fraction_addition,
    solve_fraction_operation,
    solve_frequency_table_mean,
    solve_gcd_lcm,
    solve_independent_events_probability,
    solve_linear_equation,
    solve_math_problem,
    solve_percentage_change,
    solve_percentage_of_quantity,
    solve_problem,
    solve_profit_loss,
    solve_pythagoras,
    solve_quadratic_equation,
    solve_rectangle_perimeter_and_area,
    solve_right_triangle_angle,
    solve_right_triangle_side,
    solve_rounding,
    solve_share_in_ratio,
    solve_simple_interest,
    solve_simple_probability,
    solve_simplify_ratio,
    solve_simultaneous_linear,
    solve_speed_distance_time,
    solve_statistics_summary,
    solve_trapezium_area,
    solve_triangle_area,
    solve_unit_conversion,
)
from .tts_service import tts_service
from .units import (
    Dimension,
    DimensionalError,
    Quantity,
    Unit,
    UnitRegistry,
    get_unit,
)
from .verifier import MathVerifier, verify_solution
from .visualization import render_geometry_svg, render_graph_svg

__all__ = [
    # Context
    "CurriculumContext",
    "load_context_from_db",
    # Legacy Objects
    "MathNumber",
    "MathFraction",
    "MathPercentage",
    "MathRatio",
    "MathVariable",
    "MathExpression",
    "MathEquation",
    "MathPoint",
    "MathTriangle",
    "MathDataset",
    "SolutionStep",
    "SolutionTrace",
    # AST
    "MathObject",
    "Expression",
    "Relation",
    "GeometryObject",
    "DatasetObject",
    "Constant",
    "Variable",
    "FractionExpr",
    "Term",
    "Polynomial",
    "Power",
    "Radical",
    "Logarithm",
    "BinaryOp",
    "Equation",
    "Inequality",
    "SystemOfEquations",
    "Point",
    "Vector",
    "Segment",
    "Angle",
    "Triangle",
    "Quadrilateral",
    "Circle",
    "Sector",
    "Dataset",
    "FrequencyTable",
    "SampleSpace",
    "Event",
    "ProbabilityValue",
    "MathFunction",
    "TableOfValues",
    "CoordinatePlane",
    "Money",
    "InterestModel",
    # Units
    "Dimension",
    "Unit",
    "DimensionalError",
    "UnitRegistry",
    "Quantity",
    "get_unit",
    # Solvers
    "solve_problem",
    "solve_math_problem",
    "solve_fraction_addition",
    "solve_fraction_operation",
    "solve_linear_equation",
    "solve_simultaneous_linear",
    "solve_quadratic_equation",
    "solve_triangle_area",
    "solve_rectangle_perimeter_and_area",
    "solve_circle_properties",
    "solve_trapezium_area",
    "solve_pythagoras",
    "solve_cylinder_volume_and_surface_area",
    "solve_cuboid_volume_and_surface_area",
    "solve_coordinate_distance_midpoint",
    "solve_statistics_summary",
    "solve_dataset_summary",
    "solve_frequency_table_mean",
    "solve_simple_probability",
    "solve_complementary_probability",
    "solve_independent_events_probability",
    "solve_profit_loss",
    "solve_simple_interest",
    "solve_compound_interest",
    "solve_percentage_of_quantity",
    "solve_percentage_change",
    "solve_simplify_ratio",
    "solve_share_in_ratio",
    "solve_unit_conversion",
    "solve_speed_distance_time",
    "solve_density_mass_volume",
    "solve_gcd_lcm",
    "prime_factorization",
    "solve_rounding",
    "solve_right_triangle_side",
    "solve_right_triangle_angle",
    "solve_elevation_depression",
    # Verifier
    "MathVerifier",
    "verify_solution",
    # Formulas
    "MathFormula",
    "FORMULA_REGISTRY",
    "search_formulas",
    "get_formulas_for_context",
    # Assessment Validation
    "RubricMark",
    "QuestionValidationResult",
    "AssessmentAuditReport",
    "AssessmentValidator",
    # Simulation & Narration
    "SimulationStep",
    "SimulationTrack",
    "narration_agent",
    "tts_service",
    "build_simulation_track",
    # Question Generation
    "generate_math_question",
    # Visualization
    "render_graph_svg",
    "render_geometry_svg",
    # Documents
    "EducationalDocument",
    "DocumentBlock",
    "render_educational_document_html",
]
